Poprawki stylu kodu na liście kontaktów
Samograje/kontakty pull request #30
Opened 2020-05-03 17:03 UTC by bartlomiej-szlachta

2020-05-03 17:18 UTC, kamil-rusin commented on src/screens/ContactsList/ContactsList.tsx
> +            // @ts-ignore XDDDD
XDDDDDDD

2020-05-03 17:19 UTC, kamil-rusin commented on src/screens/ContactsList/index.tsx
> +    };
XD

2020-05-03 17:19 UTC, kamil-rusin approved these changes

2020-05-04 14:40 UTC, kamil25963 commented
Robiłem npm install i czyściłem wszystkie dane z expo, dwa razy.

![95479092_241152047124816_6497028124222423040_n](https://user-images.githubusercontent.com/33577175/80978125-ee3b0180-8e25-11ea-9577-b3783dc9a96d.jpg)

2020-05-04 15:56 UTC, kamil-rusin requested changes
Błąd Kamila

2020-05-05 10:37 UTC, bartlomiej-szlachta commented
U mnie nie ma nigdzie takiego błędu 😮

2020-05-05 12:56 UTC, kamil25963 commented
> U mnie nie ma nigdzie takiego błędu 😮

Może po mergu mastera się naprawiło, dzisiaj u mnie jest w porządku.

2020-05-05 12:57 UTC, merged