Dodaj nowo - utworzony kontakt do wybranych grup
Samograje/kontakty pull request #48
Opened 2020-05-15 19:59 UTC by kamil-rusin

2020-05-16 10:36 UTC, bartlomiej-szlachta commented on src/redux/actions/addNewestContactToGroups.ts
> +        console.log('addcontact' + contacts.length);
A nie ma nie ma, zauważyłem 😁

2020-05-16 10:37 UTC, bartlomiej-szlachta requested changes
Przejrzałem kod, dla mnie gites 😎 tylko trzeba rozwiązać konflikt

2020-05-17 20:53 UTC, kamil25963 commented
U mnie nie działa. Przy tworzeniu kontaktu, jeśli dodam do niego grupy i powrócę do widoku tworzenia to nie widzę żadnych grup przypisanych do kontaktu. Czyściłem expo.

2020-05-17 20:54 UTC, kamil25963 commented
Działa poprawnie podczas edycji, gdy kontakt już istnieje, dla nowego niestety nie :(.

2020-05-17 21:06 UTC, kamil-rusin commented
Bo przycisku nie robiłem xd
Pisałem Ci 
Jak klikniesz drugi raz w dodawanie grup to widzisz jakie zaznaczyłeś 
Przycisku nie ruszyłem, więc jest do machnięcia

2020-05-17 21:06 UTC, kamil-rusin commented
Nie chciałem ingerować w jego logikę

2020-05-17 21:13 UTC, merged